### ISSUE TITLE
Help please, my code is not working.

### ISSUE THREAD

**Issue by huyphuctt** [webtorrent/community#13]
Hi everyone,

I have a problem when using webtorrent.min.js

I followed the instruction at <a href="https://webtorrent.io/intro" > Get Started</a> but it does not load anything.

The code is here:  https://jsfiddle.net/x8eb4vh9/10/

But when i run the hash with <a href="https://instant.io/#209c8226b299b308beaf2b9cd3fb49212dbd13ec" >Instant.io</a>, it works like a charm.

Could anyone help me to find where I missing?

The movie is seeding via latest version of WebTorrent Desktop on Window 10 PC.

Thanks alot.

**Comment by coolms376** [comment]
may be in your torrent file there is no .mp4 file exits that why it creates error in loading your video

**Comment by feross** [comment]
Your code works if you replace the torrent link with `magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fsintel.torrent` which actually has seeders.
