### ISSUE TITLE
Use bot to close stale issues/PRs

### ISSUE THREAD

**Issue by DiegoRBaquero** [webtorrent/community#8]
Would like to get the community feedback about using https://probot.github.io/apps/stale/

Please vote with a reaction and comment below if you have any thoughts :)

@webtorrent (Does this mention all org?)

**Comment by feross** [comment]
I like the idea. Let's test it out on a single repo to see how it works. I sent a PR to `webtorrent/webtorrent` to try this out. If it works well, we can bring it to `webtorrent/webtorrent-desktop` and perhaps others. Though, these bots do seem primarily useful on high-traffic issue trackers to help with the load.

@DiegoRBaquero, I also created a team with everyone in the org `@webtorrent/folks` for future use :)

**Comment by feross** [comment]
PR here: https://github.com/webtorrent/webtorrent/pull/1369
