### ISSUE TITLE
Using the WebTorrent API to find other Peers

### ISSUE THREAD

**Issue by ExNG** [webtorrent/community#9]
Hello,

i am kind of new to WebTorrent and WebRTC as it, and i want to make a little project for me and a few friends, i had in mind to be able to send Strings, no matter what lenght, to other peers of a torrent, wich would be privat i guess, but didn't found a way of doing this. Is that even possible? If yes, how?

**Comment by DiegoRBaquero** [comment]
You would need to implement a protocol extension and add it to the wires.
